#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

curl -o "$XDG_CONFIG_HOME"/kube-ps1.sh https://raw.githubusercontent.com/jonmosco/kube-ps1/master/kube-ps1.sh
curl -o "$XDG_CONFIG_HOME"/tmux-completion https://raw.githubusercontent.com/Bash-it/bash-it/refs/heads/master/completion/available/tmux.completion.bash


ln -sf "$PWD/kickstart.nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.bash_aliases" "$HOME"/.bash_aliases
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
sudo ln -sf "$PWD/scripts/tmux-sessionizer" /usr/local/bin/

packages=(
	kubectl
	tektoncd-cli
	helm
	fzf
	kubectx
	derailed/k9s/k9s
	fluxcd/tap/flux
	neovim
	micromamba
)

for package in "${packages[@]}"; do
	echo "Installing $package..."
	/home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

echo "All packages from the setup script have been installed."


# $HOME/.nix-profile/bin/conda init bash
# source "$HOME/.bashrc"
# conda create -n py311 python=3.11 -y
# echo "conda activate py311" >> "$HOME/.bashrc"
