#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

curl -o "$XDG_CONFIG_HOME"/kube-ps1.sh https://raw.githubusercontent.com/jonmosco/kube-ps1/master/kube-ps1.sh

ln -sf "$PWD/kickstart.nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.bash_aliases" "$HOME"/.bash_aliases
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf

packages=(
	kubectl
	tektoncd-cli
	fzf
	nvm
	kubectx
	derailed/k9s/k9s
	fluxcd/tap/flux
)

for package in "${packages[@]}"; do
	echo "Installing $package..."
	/home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

echo "All packages from the setup script have been installed."


# $HOME/.nix-profile/bin/conda init bash
# source "$HOME/.bashrc"
# conda create -n py311 python=3.11 -y
# echo "conda activate py311" >> "$HOME/.bashrc"
